name: Blog Post
description: Create a new blog post
title: "Title"
labels: ["blog-post"]
body:
  - type: textarea
    id: content
    attributes:
      label: Poem
    validations:
      required: true
