name: Auto Label Blog Issues

on:
  issues:
    types: [opened]

jobs:
  label-issue:
    runs-on: ubuntu-latest
    # Only label issues created by email from your address
    if: github.event.issue.user.login == 'github-actions[bot]' && contains(github.event.issue.body, 'From: contact@yohannparis.com')
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['blog-post']
            })
