name: Email to GitHub Issue

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  fetch-email:
    name: Check new emails and convert them to issues
    runs-on: ubuntu-latest
    environment: github-pages
    permissions:
      contents: write
      actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Run fetch-email script
        env:
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          GITHUB_REPO_NAME: ${{ github.event.repository.name }}
          GITHUB_REPO_OWNER: ${{ github.repository_owner }}
        run: |
          npm install
          npm run fetch-email
