name: Publish latest issue

on:
  workflow_dispatch:
  issues:
    types: [opened, labeled]

permissions:
  id-token: write
  issues: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  process-issue:
    name: Convert the Issue to Blog Post
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'blog-post')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create markdown file
        run: |
          # Clean title and create slug
          TITLE="${{ github.event.issue.title }}"
          POST_SLUG=$(echo "${TITLE}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-//' | sed 's/-$//')

          # Ensure directory exists
          mkdir -p posts

          # Define file path
          POST_PATH="posts/${POST_SLUG}.kit"

          # Get issue body and clean up the heading markdown
          BODY="${{ github.event.issue.body }}"
          # Remove "### Poem" heading and trim whitespace
          CLEAN_BODY=$(echo "$BODY" | sed 's/### Poem//g' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' | sed '/^$/d')

          # Create kit file with HTML structure
          cat > "${POST_PATH}" << EOF
<h1>${TITLE}</h1>
<article>
$(echo "$CLEAN_BODY" | sed 's/^/  /')
</article>
EOF

          echo "Created post at ${POST_PATH}"

      - name: Commit and push
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add posts/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Add blog post from issue #${{ github.event.issue.number }}" && git push)
      
      - name: Comment, label, and close issue
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.update({
              context.issue.number,
              context.repo.owner, 
              context.repo.repo,
              state: 'closed'
            });
  

  build:
    needs: process-issue
    name: Build and Deploy
    uses: ./.github/workflows/build-and-deploy.yml
