name: Publish latest issue

on:
  workflow_dispatch:
  issues:
    types: [labeled]

jobs:
  process-issue:
    name: Convert the Issue to Blog Post
    if: contains(github.event.issue.labels.*.name, 'blog-post')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create post from the issue
        run: |
          # Clean title and create slug
          TITLE="${{ github.event.issue.title }}"
          # Handle accented characters properly by transliterating them to ASCII equivalents
          POST_SLUG=$(echo "${TITLE}" | iconv -f utf-8 -t ascii//TRANSLIT | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-//' | sed 's/-$//')

          # Ensure directory exists
          mkdir -p posts

          # Define file path
          POST_PATH="posts/${POST_SLUG}.kit"

          # Get issue body and clean up the heading markdown
          BODY="${{ github.event.issue.body }}"
          # Remove "### Poem" heading and trim whitespace
          CLEAN_BODY=$(echo "$BODY" | sed 's/### Poem//g' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' | sed '/^$/d')

          # Create kit file with HTML structure
          cat > "${POST_PATH}" << EOL
          <h1>${TITLE}</h1>
          <article>
          $(echo "$CLEAN_BODY" | sed 's/$/&<br>/' | sed 's/^/  /')
          </article>
          EOL

          echo "Created post at ${POST_PATH}"

      - name: Commit and push
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add posts/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Add blog post from issue #${{ github.event.issue.number }}" && git push)

      - name: Comment, label, and close issue
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed'
            });

  build:
    needs: process-issue
    name: Build and deploy the blog
    uses: ./.github/workflows/build-and-deploy.yml
    permissions:
      contents: write
      id-token: write
